allowBuilds:
  '@fortawesome/fontawesome-common-types': false
  '@fortawesome/fontawesome-free': false
  '@fortawesome/fontawesome-svg-core': false
  '@fortawesome/free-solid-svg-icons': false
  esbuild: true
