import { ArrowRight, BookOpen, ExternalLink, Landmark, Search, X } from "lucide-react";
import { useMemo, useState } from "react";
import kantPortrait from "../assets/philosophers/kant-becker.jpg";
import sartrePortrait from "../assets/philosophers/sartre-cutout-v2.png";
import socratesPortrait from "../assets/philosophers/socrates-cutout.png";
import { philosophers, type Philosopher } from "../data/philosophers";
const portraits={socrates:socratesPortrait,kant:kantPortrait,sartre:sartrePortrait};
const unique=(v:string[])=>[...new Set(v)].sort((a,b)=>a.localeCompare(b,"zh-CN"));
export function PhilosopherAtlasPage(){
 const initialSearch=new URLSearchParams(window.location.hash.split("?")[1]??"").get("search")??"";
 const [query,setQuery]=useState(initialSearch),[era,setEra]=useState(""),[region,setRegion]=useState(""),[tradition,setTradition]=useState(""),[selectedId,setSelectedId]=useState("socrates");
 const eras=useMemo(()=>unique(philosophers.map(p=>p.era)),[]),regions=useMemo(()=>unique(philosophers.map(p=>p.region)),[]),traditions=useMemo(()=>unique(philosophers.flatMap(p=>p.traditions)),[]);
 const filtered=useMemo(()=>philosophers.filter(p=>{const q=query.trim().toLocaleLowerCase("zh-CN");return(!q||[p.name,p.englishName,p.summary,...p.coreIdeas,...p.works].join(" ").toLocaleLowerCase("zh-CN").includes(q))&&(!era||p.era===era)&&(!region||p.region===region)&&(!tradition||p.traditions.includes(tradition));}),[query,era,region,tradition]);
 const selected=filtered.find(p=>p.id===selectedId)??filtered[0]??philosophers[0];
 const related=selected.relatedIds.map(id=>philosophers.find(p=>p.id===id)).filter((p):p is Philosopher=>Boolean(p));
 const clear=()=>{setQuery("");setEra("");setRegion("");setTradition("");};
 return <main className="philosopher-atlas-page"><header className="atlas-hero"><p className="section-kicker">WESTERN PHILOSOPHER ATLAS</p><h1>西方哲学家图鉴</h1><p>沿着时代、地域与思想传统进入西方哲学史的馆藏目录。每个人物都是继续阅读与回到自身档案的入口。</p><div><span><Landmark size={16}/>{philosophers.length} 位馆藏人物</span><span>{eras.length} 个时代分区</span><span>{traditions.length} 条思想传统</span></div></header>
 <section className="atlas-filter-rail" aria-label="筛选哲学家图鉴"><label className="atlas-search"><span>检索人物或思想</span><div><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="姓名、核心思想或代表著作"/></div></label><label><span>时代</span><select value={era} onChange={e=>setEra(e.target.value)}><option value="">全部时代</option>{eras.map(v=><option key={v}>{v}</option>)}</select></label><label><span>地区</span><select value={region} onChange={e=>setRegion(e.target.value)}><option value="">全部地区</option>{regions.map(v=><option key={v}>{v}</option>)}</select></label><label><span>传统</span><select value={tradition} onChange={e=>setTradition(e.target.value)}><option value="">全部传统</option>{traditions.map(v=><option key={v}>{v}</option>)}</select></label>{query||era||region||tradition?<button onClick={clear}><X size={15}/>清除</button>:null}</section>
 {filtered.length===0?<section className="atlas-empty"><h2>这条思想回廊暂时没有人物</h2><button onClick={clear}>恢复全部图鉴</button></section>:<div className="atlas-workspace"><aside className="atlas-index" aria-label="哲学家馆藏索引"><header><span>馆藏索引</span><strong>{filtered.length} / {philosophers.length}</strong></header><div>{filtered.map((p,i)=><button className={p.id===selected.id?"active":""} key={p.id} onClick={()=>setSelectedId(p.id)}><small>{String(i+1).padStart(2,"0")}</small><span><strong>{p.name}</strong><em>{p.englishName}</em></span><i>{p.era}</i></button>)}</div></aside><article className="atlas-exhibit"><div className="atlas-portrait-stage">{selected.portrait?<img src={portraits[selected.portrait]} alt={selected.name+"肖像"}/>:<div className="atlas-name-seal"><span>Φ</span><strong>{selected.name.slice(0,2)}</strong><small>PORTRAIT ARCHIVE</small></div>}<div className="atlas-era-mark">{selected.era}<span>{selected.life}</span></div></div><div className="atlas-exhibit-copy"><p className="section-kicker">COLLECTION / {selected.region}</p><h2>{selected.name}</h2><h3>{selected.englishName}</h3><p className="atlas-summary">{selected.summary}</p><dl><div><dt>思想传统</dt><dd>{selected.traditions.map(v=><span key={v}>{v}</span>)}</dd></div><div><dt>核心思想</dt><dd>{selected.coreIdeas.map(v=><span key={v}>{v}</span>)}</dd></div><div><dt>代表著作</dt><dd>{selected.works.map(v=><span key={v}>{v}</span>)}</dd></div></dl><section className="atlas-relations"><span>思想关系</span><div>{related.map(p=><button key={p.id} onClick={()=>setSelectedId(p.id)}>{p.name}<ArrowRight size={13}/></button>)}</div></section><footer><a className="atlas-archive-link" href={"#archive?philosopher="+encodeURIComponent(selected.name)}><BookOpen size={15}/>查看相关思想档案</a><a href={selected.sourceUrl} target="_blank" rel="noreferrer">资料来源：{selected.sourceLabel}<ExternalLink size={13}/></a></footer></div></article></div>}
 </main>;
}
